server:
  port: 8081

spring:
  application:
    name: ruuby-gateway
  profiles:
    active: dev
  redis:
    host: r-2zebca7d4628bac4.redis.rds.aliyuncs.com
    port: 6379
  password: Qrbrqj88
  cloud:
    loadbalancer:
      # 灰度发布支持
      gray:
        enabled: true
    gateway:
      gray:
        enabled: true
        matches:
          - 123
          - 456
          - 10.1.1.10
      routes:
        - id: account-svc
          uri: lb://account-svc
          predicates:
            - Path=/gateway/account/**
          filters:
            - StripPrefix=1
            # url黑名单 这是一个局部过滤器
            # - name: BlackListUrlFilter
            #   args:
            #     blackListUrl:
            #       - /account/list
            # 鉴权过滤器
            # - name: AuthFilter
            #   args:
            #     type: jwt
            #     publicKey: 11111
        - id: monitor-svc
          uri: lb://monitor-svc
          predicates:
            - Path=/gateway/monitor/actuator/**
          filters:
            - StripPrefix=1
        - id: order-svc
          uri: lb://order-svc
          predicates:
            - Path=/gateway/order/**
          filters:
            - StripPrefix=1
    sentinel:
      # 取消控制台懒加载
      eager: true
      transport:
        # 控制台地址
        dashboard: 127.0.0.1:8080
      # nacos配置持久化
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-sentinel-${spring.profiles.active}.json
            namespace: 3ef5e608-6ee8-4881-8e50-ed47a5a04af2
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: gw-flow
      filter:
        enabled: true
      # 配置默认fallback，也可以编码自定义fallback
      # scg.fallback:
      #     mode: response
      #     response-status: 444
      #     response-body: 1234
      # scg:
      #   order: -100

# Xss过滤
security:
  xss:
    enabled: true
    excludeUrls:
      - /account/v2/**
      - /order/v2/**
# 指标采集
management:
  health:
    redis:
      enabled: false
    sentinel:
      enabled: false
    ldap:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always