server:
  port: 8089
spring:
  application:
    name: order-svc
  profiles:
    active: dev
  # 解决springboot 2.6以上集成swagger3报错问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      username: "nacos"
      password: "nacos"
      discovery:
        # 服务注册中心地址
        server-addr: 127.0.0.1:8848
        # 阿里云平台ak，sk
        # access-key:
        # secret-key:
        namespace: 3ef5e608-6ee8-4881-8e50-ed47a5a04af2
      config:
        server-addr: 127.0.0.1:8848
        # 阿里云平台ak，sk
        # access-key:
        # secret-key:
        # 配置文件格式
        file-extension: yml
        shared-configs:
          - ${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
        namespace: 3ef5e608-6ee8-4881-8e50-ed47a5a04af2
        group: DEFAULT-GROUP
    # sentinel支持
    sentinel:
      # 取消控制台懒加载
      eager: true
      transport:
        dashboard: 127.0.0.1:8080
      # 动态数据源支持
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-sentinel-${spring.profiles.active}.json
            namespace: 3ef5e608-6ee8-4881-8e50-ed47a5a04af2
            groupId: DEFAULT_GROUP
            data-type: json
            # 具体配置参考com.alibaba.cloud.sentinel.datasource.RuleType
            rule-type: flow
    stream:
      function:
        definition: producer
      # Spring Cloud Stream RocketMQ配置项
      rocketmq:
        binder:
          # name server 配置
          name-server: 172.17.10.179:9876
          # 阿里云ak sk配置
          # accessKey:
          # secretKey:
          # 是否为Producer和Consumer开启消息轨迹功能 默认 true
          # enableMsgTrace: false
          # 消息轨迹开启后存储的 topic 名称 默认 RMQ_SYS_TRACE_TOPIC
          # customizedTraceTopic: RMQ_SYS_TRACE_TOPIC
        bindings:
          # 生成规则 function.definition - out - index（坑）
          producer-out-0:
            producer:
              # 是否开启生产，默认为 true
              enabled: true
              # 生产者分组
              group: output_1
              # 是否同步发送消息，默认为 false 异步
              # sync: true
          producer-out-1:
            producer:
              # 是否开启生产，默认为 true
              enabled: true
              # 生产者分组
              group: output_2
              # 是否同步发送消息，默认为 false 异步
              # sync: true
      # Binding配置项
      bindings:
        producer-out-0:
          # RocketMQ Topic
          destination: TPC_Test_dev
          # 内容格式
          # content-type: application/json
        producer-out-1:
          # RocketMQ Topic
          destination: TPC_Test_dev
          # 内容格式
          # content-type: application/json
# feign支持sentinel
feign:
  sentinel:
    enabled: true

# RestTemplate支持sentinel
resttemplate:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
# swagger配置
swagger:
  enabled: true
  basePackage: io.redick.cloud.order
  title: Order模块接口文档
  description: Order模块接口文档
  version: 0.0.1
  terms-of-service-ur: io.redick.cloud.order
