server:
  port: 8088
spring:
  application:
    name: account-svc
  profiles:
    active: dev
  # 解决springboot 2.6以上集成swagger3报错问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      username: "nacos"
      password: "nacos"
      discovery:
        # 服务注册中心地址
        server-addr: 127.0.0.1:8848
        # 阿里云平台ak，sk
        # access-key:
        # secret-key:
        namespace: 3ef5e608-6ee8-4881-8e50-ed47a5a04af2
      config:
        server-addr: 127.0.0.1:8848
        # 阿里云平台ak，sk
        # access-key:
        # secret-key:
        # 配置文件格式
        file-extension: yml
        shared-configs:
          - ${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
        namespace: 3ef5e608-6ee8-4881-8e50-ed47a5a04af2
        group: DEFAULT-GROUP


management:
  endpoints:
    web:
      exposure:
        include: "*"
# swagger配置
swagger:
  enabled: true
  basePackage: io.redick.cloud.account
  title: Account模块接口文档
  description: Account模块接口文档
  version: 0.0.1
  terms-of-service-ur: io.redick.cloud.account
